apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-config.resourceName" (list . "configmap") | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "generic-config.labels" (list . "configmap") | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap.config }}
  {{ $key }}: {{ $value | default "" | quote }}
{{- end }}
