{{- range $externalSecretComponent, $externalSecretValues := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "generic-config.resourceName" (list $ "es" $externalSecretComponent) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "generic-config.labels" (list $ "external-secrets") | nindent 4 }}
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: "{{ $.Values.project }}-secretstore"
    kind: "{{ $externalSecretValues.secretStoreKind }}"
  target:
    name: {{ include "generic-config.resourceName" (list $ "es" $externalSecretComponent) | quote }}
    {{- if hasKey $externalSecretValues "template" }}
    template:
      engineVersion: v2
      type: {{ $externalSecretValues.template.type }}
      data:
        {{- toYaml $externalSecretValues.template.data | nindent 8 }}
    {{- end }}
  {{- if hasKey $externalSecretValues "template" }}
  data:
    - secretKey: {{ $externalSecretValues.template.secretKey }}
      remoteRef:
        {{- if hasKey $externalSecretValues "secretsManagerNameOverride" }}
        key: {{ $externalSecretValues.secretsManagerNameOverride | quote }}
        {{- else }}
        key: "{{ $.Values.project }}-{{ $externalSecretComponent }}-{{ $.Values.environment }}"
        {{- end }}
  {{- else }}
  dataFrom:
    - extract:
        {{- if hasKey $externalSecretValues "secretsManagerNameOverride" }}
        key: {{ $externalSecretValues.secretsManagerNameOverride | quote }}
        {{- else }}
        key: "{{ $.Values.project }}-{{ $externalSecretComponent }}-{{ $.Values.environment }}"
        {{- end }}
  {{- end }}
{{- end }}
