{{- range $serviceAccountComponent, $serviceAccountValues := .Values.serviceAccounts }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: {{ include "generic-config.resourceName" (list $ $.Values.environment $serviceAccountComponent) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $serviceAccountValues.roleArn | quote }}
  labels:
    {{- include "generic-config.labels" (list $ $serviceAccountComponent) | nindent 4 }}
{{- end }}
