{{- range $ingressComponent, $ingressValues := .Values.ingresses }}
{{- if or $ingressValues.enabled (not (hasKey $ingressValues "enabled")) }}
{{- if $ingressValues.oidc.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "generic-config.resourceName" (list $ "alb-controller-secret-access-role" $ingressComponent) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
rules:
  - apiGroups:
      - ""
    resourceNames:
      - {{ $ingressValues.oidc.externalSecretName | quote }}
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "generic-config.resourceName" (list $ "alb-controller-secret-access-rolebinding" $ingressComponent) | quote }}
  namespace: {{ $.Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "generic-config.resourceName" (list $ "alb-controller-secret-access-role" $ingressComponent) | quote }}
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-system
{{- end }}
{{- end }}
{{- end }}
