{{- if .Values.efs.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "generic-config.fullname" . }}-{{ .Values.environment }}-efs"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "generic-config.labels" (list $ "efs-sa") | nindent 4 -}}
{{- end }}
