apiVersion: v2
name: generic-config
description: A generic Helm chart for Kubernetes configuration resources.
type: application
version: 1.1.0
dependencies:
  - name: local-redis
    version: 0.4.0
    repository: s3://bucket-where-redis-chart-is
    condition: dependencies.local-redis.enabled
